version: '3'

services:
  media-server:
    image: ${repo_pre}dips/media-server${tag}
    restart: always
    ports:
      - 80:5000
    volumes:
      - "/mnt/dips/Linjeorganisasjon/Utviklingsavdelingen/Video utviklerforum, sprintdemo, m√∏ter og kurs/Utviklerforum/Dev days 2018/DevDays2018Video":/app/wwwroot/Conference/DevDays2018
  